### ISSUE TITLE
Add a CONTRIBUITION.md file

### ISSUE THREAD

**Issue by NathanTarbert** [NathanTarbert/Allocate#107]
**Description:**
Currently, the CONTRIBUTING.md file for DefiKids is located in the .github directory. To ensure that contributors can easily access and refer to the contribution guidelines, it should be also added to the root directory of the defikids-dapp repository.

**Expected Behavior:**
The CONTRIBUTING.md file should be located in the root directory of the repository so that it is readily visible and accessible to all contributors.

**Steps to Implement:**
Copy the CONTRIBUTING.md file from the .github directory to the root directory of the DefiKids app repository.
Update any references or links within the the guide to reflect the new location of the CONTRIBUTING.md file.

**Additional Information:**
This change will streamline the contribution process and make it easier for contributors to find and reference the guidelines when making contributions to DefiKids.

**Comment by ankits57** [comment]
hey, i will do the changes

**Comment by Tashuuuu** [comment]
I can see it is already in the root directory
