### ISSUE TITLE
Add https://contrib.rocks/ to defikids-dapp README.md

### ISSUE THREAD

**Issue by NathanTarbert** [NathanTarbert/Allocate#115]
Please add the `contribute.rocks` image of stargazers to the defikids-dapp README above the `Contact Us` section.

**Comment by smoll-xiao** [comment]
If my request gets merged do I get the hacktoberfest-accepted label?

**Comment by smoll-xiao** [comment]
just updated my pr

**Comment by NathanTarbert** [comment]
@smoll-xiao, I added the `hacktoberfest-accepted` label

**Comment by abhinab-choudhury** [comment]
Can I work on this issue
